console.log("-----------------------#  Receta  #------------------------------------------------------");
console.log("Budin de BANANA");
console.log("-----------------------# Elementos  #---------------------------------------------------");
console.log("Paso 1--> Preparar ingredientes: 2 banana, 2 huevos, 1/2 taza de leche, 1/2 taza de aceite, 200g de azucar,etc... ");
console.log("Paso 2--> Prepara elementos: 1 Molde, 1 Licuadora, Horno");
console.log("------------------------#  Preparación  #------------------------------------------------");
console.log("Paso 3--> Colocar en licuadora la banana, los huevos, la leche, el aceite, el azucar y prender Horno");
console.log("Paso 4--> Licuar");
console.log("Paso 5--> Pasar la mezcla a un bols");
console.log("Paso 6--> Agregar avena y harina");
console.log("Paso 7--> Sumar nueces y/o Chocolate a gusto");
console.log("Paso 8--> Mezclar");
console.log("Paso 9--> Harinar molde");
console.log("Paso 10--> Pasar la mezcla a el molde");
console.log("Paso 11--> Colocar el molde con la mezcla en el horno por 35 min.");
console.log("Paso 12--> Sacar del horno y dejar enfriar");
console.log("Paso 13--> Desmoldear y  cortar en trozos");
console.log("Paso 14--> Lista para comer");
console.log("-----------------------#  Fin  #------------------------------------------------------");
